<?php
return [
    // --- Chaves Originais ---
    "welcome" => "مرحبًا بكم في مركز شحن الشرق الأوسط وشمال إفريقيا",
    "login" => "تسجيل الدخول",
    "logout" => "تسجيل الخروج",
    "company" => "شركة",
    "address" => "عنوان",
    "vehicle" => "مركبة",
    "quote" => "طلب عرض أسعار",
    "dashboard" => "لوحة التحكم",
    "companies" => "الشركات",
    "vehicles" => "المركبات",
    "quotes" => "عروض الأسعار",
    "name" => "الاسم",
    "email" => "البريد الإلكتروني",
    "phone" => "الهاتف",
    "type" => "النوع",
    "capacity" => "السعة",
    "plate" => "اللوحة/المعرف",
    "origin" => "المنشأ",
    "destination" => "الوجهة",
    "start_date" => "تاريخ البداية",
    "end_date" => "تاريخ النهاية",
    "value" => "القيمة",
    "actions" => "الإجراءات",
    "edit" => "تعديل",
    "delete" => "حذف",
    "save" => "حفظ",
    "cancel" => "إلغاء",
    "add_new" => "إضافة جديد",
    "search" => "بحث",
    "total" => "المجموع",

    // --- Novas Chaves (Login) ---
    "username_placeholder" => "اسم المستخدم",
    "password_placeholder" => "كلمة المرور",
    "login_button" => "دخول",
    "login_error" => "اسم المستخدم أو كلمة المرور غير صحيحة!",

    // --- Novas Chaves (Dashboard) ---
    "welcome_user" => "أهلاً بك",
    "registered_companies" => "الشركات المسجلة",
    "manage_companies" => "إدارة الشركات",
    "registered_vehicles" => "المركبات المسجلة",
    "manage_vehicles" => "إدارة المركبات",
    "generated_quotes" => "عروض الأسعار التي تم إنشاؤها",
    "manage_quotes" => "إدارة عروض الأسعار",
    "total_value" => "القيمة الإجمالية",
    "view_reports" => "عرض التقارير",
    "quick_actions" => "إجراءات سريعة",
    "add_new_company" => "إضافة شركة جديدة",
    "add_new_vehicle" => "إضافة مركبة جديدة",
    "add_new_quote" => "إنشاء عرض أسعار جديد",

    // --- Novas Chaves (cadempresa.php) ---
    "company_registration" => "تسجيل الشركات",
    "company_name_label" => "اسم الشركة:",
    "company_cnpj_label" => "الرقم الضريبي/المعرف:",
    "company_phone_label" => "الهاتف:",
    "register_company_btn" => "تسجيل الشركة",
    "clear_btn" => "مسح",
    "registered_companies_list" => "الشركات المسجلة",
    "cnpj_id_header" => "المعرف/الرقم الضريبي",
    "confirm_delete_message" => "هل أنت متأكد؟",
    "company_registered" => "تم تسجيل الشركة بنجاح!",
    "company_error" => "خطأ في تسجيل الشركة.",
    "company_updated" => "تم تحديث الشركة بنجاح!",
    "company_update_error" => "خطأ في تحديث الشركة.",
    "company_deleted" => "تم حذف الشركة بنجاح!",
    "company_delete_error" => "خطأ في حذف الشركة.",

    // --- Chaves Página Inicial ---
    "home_title" => "مركز شحن الشرق الأوسط وشمال أفريقيا - منصة لوجستية للأعمال",
    "hero_title" => "حلّك المتكامل لإدارة الشحن في منطقة الشرق الأوسط وشمال أفريقيا",
    "hero_subtitle" => "مركز شحن الشرق الأوسط وشمال أفريقيا هو منصة ويب قوية مصممة لتحسين إدارة نقل البضائع للشركات متعددة الجنسيات في الشرق الأوسط وشمال أفريقيا.",
    "hero_button" => "الوصول إلى بوابة العملاء",
    "features_title" => "الميزات الرئيسية:",
    "feature_1" => "تسجيل وإدارة الشركات بعناوين متعددة.",
    "feature_2" => "تحكم تفصيلي في مركبات الأسطول.",
    "feature_3" => "طلب وإنشاء عروض أسعار النقل بكفاءة.",
    "feature_4" => "دعم متعدد اللغات: الإنجليزية، العربية، والفرنسية.",
    "contact_title" => "تواصل معنا",
    "contact_subtitle" => "لمزيد من المعلومات، يرجى التواصل معنا.",
    "footer_copyright" => "&copy; 2025 مركز شحن الشرق الأوسط وشمال أفريقيا. جميع الحقوق محفوظة.",

        // ... (outras chaves)
    "companies_title" => "الشركات",
    "addresses_title" => "العناوين",
    "country_label" => "البلد:",
    "city_label" => "المدينة:",
    "street_label" => "الشارع:",
    "number_label" => "الرقم:",
    "add_address_btn" => "إضافة عنوان",
    "remove_address_btn" => "إزالة العنوان",
    "view_addresses_btn" => "عرض العناوين",

        
    "vehicles_title" => "المركبات",
    "vehicle_registration" => "تسجيل مركبة",
    "vehicle_model_label" => "الموديل:",
    "vehicle_brand_label" => "العلامة التجارية:",
    "vehicle_plate_label" => "رقم اللوحة/المعرف:",
    "register_vehicle_btn" => "تسجيل مركبة",
    "registered_vehicles_list" => "المركبات المسجلة",
    "model" => "الموديل",
    "brand" => "العلامة التجارية",
    "vehicle_deleted" => "تم حذف المركبة بنجاح!",
    "vehicle_delete_error" => "خطأ في حذف المركبة.",
    "vehicle_updated" => "تم تحديث المركبة بنجاح!",
    "vehicle_update_error" => "خطأ في تحديث المركبة.",
    "vehicle_registered" => "تم تسجيل المركبة بنجاح!",
    "vehicle_error" => "خطأ في تسجيل المركبة.",
];
?>