<?php
return [
    // --- Chaves Originais ---
    "welcome" => "Welcome to MENA Freight Hub",
    "login" => "Login",
    "logout" => "Logout",
    "company" => "Company",
    "address" => "Address",
    "vehicle" => "Vehicle",
    "quote" => "Request a Quote",
    "dashboard" => "Dashboard",
    "companies" => "Companies",
    "vehicles" => "Vehicles",
    "quotes" => "Quotes",
    "name" => "Name",
    "email" => "Email",
    "phone" => "Phone",
    "type" => "Type",
    "capacity" => "Capacity",
    "plate" => "Plate/ID",
    "origin" => "Origin",
    "destination" => "Destination",
    "start_date" => "Start Date",
    "end_date" => "End Date",
    "value" => "Value",
    "actions" => "Actions",
    "edit" => "Edit",
    "delete" => "Delete",
    "save" => "Save",
    "cancel" => "Cancel",
    "add_new" => "Add New",
    "search" => "Search",
    "total" => "Total",

    // --- Novas Chaves (Login) ---
    "username_placeholder" => "Username",
    "password_placeholder" => "Password",
    "login_button" => "Login",
    "login_error" => "Incorrect username or password!",

    // --- Novas Chaves (Dashboard) ---
    "welcome_user" => "Welcome",
    "registered_companies" => "Registered Companies",
    "manage_companies" => "Manage Companies",
    "registered_vehicles" => "Registered Vehicles",
    "manage_vehicles" => "Manage Vehicles",
    "generated_quotes" => "Generated Quotes",
    "manage_quotes" => "Manage Quotes",
    "total_value" => "Total Value",
    "view_reports" => "View Reports",
    "quick_actions" => "Quick Actions",
    "add_new_company" => "Add New Company",
    "add_new_vehicle" => "Add New Vehicle",
    "add_new_quote" => "Generate New Quote",

    // --- Novas Chaves (cadempresa.php) ---
    "company_registration" => "Company Registration",
    "company_name_label" => "Company Name:",
    "company_cnpj_label" => "CNPJ/Tax ID:",
    "company_phone_label" => "Phone:",
    "register_company_btn" => "Register Company",
    "clear_btn" => "Clear",
    "registered_companies_list" => "Registered Companies",
    "cnpj_id_header" => "CNPJ/ID",
    "confirm_delete_message" => "Are you sure?",
    "company_registered" => "Company registered successfully!",
    "company_error" => "Error registering company.",
    "company_updated" => "Company updated successfully!",
    "company_update_error" => "Error updating company.",
    "company_deleted" => "Company deleted successfully!",
    "company_delete_error" => "Error deleting company.",
    // --- Chaves Página Inicial ---
    "home_title" => "MENA Freight Hub - B2B Logistics Platform",
    "hero_title" => "Your Complete Solution for Freight Management in the MENA Region",
    "hero_subtitle" => "MENA Freight Hub is a robust web platform designed to optimize freight management for multinational companies in the Middle East and North Africa.",
    "hero_button" => "Access Customer Portal",
    "features_title" => "Main Features:",
    "feature_1" => "Registration and management of companies with multiple addresses.",
    "feature_2" => "Detailed control of fleet vehicles.",
    "feature_3" => "Efficiently request and generate transport quotes.",
    "feature_4" => "Multilingual support: English, Arabic, and French.",
    "contact_title" => "Get in Touch",
    "contact_subtitle" => "For more information, please contact us.",
    "footer_copyright" => "&copy; 2025 MENA Freight Hub. All rights reserved.",

        // ... (outras chaves)
    "companies_title" => "Companies",
    "addresses_title" => "Addresses",
    "country_label" => "Country:",
    "city_label" => "City:",
    "street_label" => "Street:",
    "number_label" => "Number:",
    "add_address_btn" => "Add Address",
    "remove_address_btn" => "Remove Address",
    "view_addresses_btn" => "View Addresses"
];
?>