<?php
return [
    // --- Chaves Originais ---
    "welcome" => "Bienvenue sur MENA Freight Hub",
    "login" => "Connexion",
    "logout" => "Déconnexion",
    "company" => "Entreprise",
    "address" => "Adresse",
    "vehicle" => "Véhicule",
    "quote" => "Demander un devis",
    "dashboard" => "Tableau de bord",
    "companies" => "Entreprises",
    "vehicles" => "Véhicules",
    "quotes" => "Devis",
    "name" => "Nom",
    "email" => "Email",
    "phone" => "Téléphone",
    "type" => "Type",
    "capacity" => "Capacité",
    "plate" => "Plaque/ID",
    "origin" => "Origine",
    "destination" => "Destination",
    "start_date" => "Date de début",
    "end_date" => "Date de fin",
    "value" => "Valeur",
    "actions" => "Actions",
    "edit" => "Modifier",
    "delete" => "Supprimer",
    "save" => "Enregistrer",
    "cancel" => "Annuler",
    "add_new" => "Ajouter nouveau",
    "search" => "Rechercher",
    "total" => "Total",
    
    // --- Novas Chaves (Login) ---
    "username_placeholder" => "Nom d'utilisateur",
    "password_placeholder" => "Mot de passe",
    "login_button" => "Se connecter",
    "login_error" => "Nom d'utilisateur ou mot de passe incorrect !",

    // --- Novas Chaves (Dashboard) ---
    "welcome_user" => "Bienvenue",
    "registered_companies" => "Entreprises Enregistrées",
    "manage_companies" => "Gérer les Entreprises",
    "registered_vehicles" => "Véhicules Enregistrés",
    "manage_vehicles" => "Gérer les Véhicules",
    "generated_quotes" => "Devis Générés",
    "manage_quotes" => "Gérer les Devis",
    "total_value" => "Valeur Totale",
    "view_reports" => "Voir les Rapports",
    "quick_actions" => "Actions Rapides",
    "add_new_company" => "Ajouter une Nouvelle Entreprise",
    "add_new_vehicle" => "Ajouter un Nouveau Véhicule",
    "add_new_quote" => "Générer un Nouveau Devis",
    
    // --- Novas Chaves (cadempresa.php) ---
    "company_registration" => "Enregistrement des Entreprises",
    "company_name_label" => "Nom de l'Entreprise :",
    "company_cnpj_label" => "N° d'Identification Fiscale :",
    "company_phone_label" => "Téléphone :",
    "register_company_btn" => "Enregistrer l'Entreprise",
    "clear_btn" => "Effacer",
    "registered_companies_list" => "Liste des Entreprises",
    "cnpj_id_header" => "ID/N° Fiscal",
    "confirm_delete_message" => "Êtes-vous sûr ?",
    "company_registered" => "Entreprise enregistrée avec succès !",
    "company_error" => "Erreur lors de l'enregistrement.",
    "company_updated" => "Entreprise mise à jour avec succès !",
    "company_update_error" => "Erreur de mise à jour.",
    "company_deleted" => "Entreprise supprimée avec succès !",
    "company_delete_error" => "Erreur de suppression.",

    // --- Chaves Página Inicial ---
    "home_title" => "MENA Freight Hub - Plateforme Logistique B2B",
    "hero_title" => "Votre Solution Complète pour la Gestion de Fret dans la Région MENA",
    "hero_subtitle" => "MENA Freight Hub est une plateforme web robuste, conçue pour optimiser la gestion du transport de marchandises pour les entreprises multinationales au Moyen-Orient et en Afrique du Nord.",
    "hero_button" => "Accéder au Portail Client",
    "features_title" => "Caractéristiques Principales :",
    "feature_1" => "Enregistrement et gestion d'entreprises avec plusieurs adresses.",
    "feature_2" => "Contrôle détaillé des véhicules de la flotte.",
    "feature_3" => "Demande et génération efficaces de devis de transport.",
    "feature_4" => "Support multilingue : Anglais, Arabe et Français.",
    "contact_title" => "Contactez-nous",
    "contact_subtitle" => "Pour plus d'informations, veuillez nous contacter.",
    "footer_copyright" => "&copy; 2025 MENA Freight Hub. Tous droits réservés."
];
?>